name: golangci-lint
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      GOPATH: /home/runner/go
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: golangci/golangci-lint-action@v6.5.2
      - run: git diff --exit-code
